version: "3.7"

services:
  nginx: 
    image: nginx:1.15-alpine
    ports:
      - "80:80"
    volumes:
      - "./docker/nginx/etc/default.conf:/etc/nginx/conf.d/default.conf"
      - "./src:/usr/share/nginx/html"
  php:
    image: php:7.3-fpm-alpine
    volumes:
      - "./src:/usr/share/nginx/html"